---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 15575.
--- DateTime: 2025/3/10 下午8:50
---

-- 1.1 优惠券id
local voucherId = ARGV[1]
-- 1.2 用户id
local userId=ARGV[2]
-- 1.3订单id
local orderId=ARGV[3]

-- 2.有关数据key
local stockKey='seckill:stock:'.. voucherId
local orderKey ='seckill:order:'.. voucherId

-- 脚本业务

--判断优惠券是否充足
if(tonumber(redis.call('get',stockKey))<=0) then
    -- 库存不足，返回1
    return 1
end
-- 判断用户是否下单
if(redis.call('sismember',orderKey,userId)==1) then
    --存在，说明是重复下单
    return 2
end
-- 扣库存
redis.call('incrby',stockKey,-1)
-- 下单
redis.call('sadd',orderKey,userId)
--发送消息到队列当中
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0

